### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by to-yan** [to-yan/furima-36407#20]
# URL
https://furima-36407.herokuapp.com/

# Bsic認証 IDとpassword
satoru
03091124

# 出品者
aaa@aaa.com
1212www

# 購入者
bbb@bbb.com
1212www

**Comment by takumi0530** [comment]
@to-yan さん、お待たせいたしました。ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

### **[修正依頼箇所]**

- [ ] **エラーハンドリングの際、重複したエラーメッセージが表示されないこと（新規登録）**
「Email can't be blank」の表示が重複していました。
<img width="268" alt="スクリーンショット 2021-08-16 10 40 39" src="https://user-images.githubusercontent.com/76197191/129500727-a1edade2-5049-4f3b-9e3d-01f2073e60f7.png">

- [ ] **カテゴリーは、「---、メンズ、レディース、ベビー・キッズ、インテリア・住まい・小物、本・音楽・ゲーム、おもちゃ・ホビー・グッズ、家電・スマホ・カメラ、スポーツ・レジャー、ハンドメイド、その他」の11項目が表示されること（--- は初期値として設定すること）**
現状、「ベビー・キッズ・小物」となっておりますが、正しくは「ベビー・キッズ」となります。

- [ ] **配送先の情報として、郵便番号・都道府県・市区町村・番地・電話番号が必須であること**
- [ ] **エラーハンドリングができていること（入力に問題がある状態で「購入」ボタンが押された場合、情報は受け入れられず、購入ページでエラーメッセージが表示されること）**
現状、都道府県の記載がなくても購入できてしまいます。また、都道府県に関するエラーメッセージも表示されませんでした。

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by to-yan** [comment]
添削ありがとうございます。
修正を行いましたので、ご確認をよろしくお願いいたします。

**Comment by takumi0530** [comment]
@to-yan さん、フリマアプリ達成要件分の開発お疲れ様でした！
ここまで培ってきた知識や学びを活かして、これからは下記例のようなさらなる学習に取り組みましょう！

**＜今後の学習例＞**
```
・フリマアプリ追加実装
・オリジナルアプリ開発
・今まで学んできた言語あるいは新言語の学習　等
```

今後の学習方針や学習計画については、担当ライフコーチまでお気軽にご相談くださいませ。
また、以下提出物に関するリマインドです。

**＜提出物＞**
```
・最終課題説明文（フリマアプリ達成要件および、追加実装内容にて作成をお願いいたします）
・要件定義（追加実装あるいは、オリジナルアプリの内容で作成をお願いいたします）
```
**※提出期日については、最終課題開始時に配布した下記動画にてご確認いただきますようお願いいたします。**

**＜最終課題に関する締め切りについての動画＞**
`https://master.tech-camp.in/v2/curriculums/6852`

今後の流れに関して、もしご不明点がございましたら、
担当ライフコーチまでお気兼ねなくお申し付けくださいませ。
![最終課題終了_おめでとう画像2](https://user-images.githubusercontent.com/76197191/129509598-b009ea0f-7dfc-48ab-a8c2-81c26a211ed9.png)

**Comment by to-yan** [comment]
ありがとうございました！！
